// Generated by gencpp from file simple_applications/CircularMotionRequest.msg
// DO NOT EDIT!


#ifndef SIMPLE_APPLICATIONS_MESSAGE_CIRCULARMOTIONREQUEST_H
#define SIMPLE_APPLICATIONS_MESSAGE_CIRCULARMOTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_applications
{
template <class ContainerAllocator>
struct CircularMotionRequest_
{
  typedef CircularMotionRequest_<ContainerAllocator> Type;

  CircularMotionRequest_()
    : radius(0.0)  {
    }
  CircularMotionRequest_(const ContainerAllocator& _alloc)
    : radius(0.0)  {
  (void)_alloc;
    }



   typedef double _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::simple_applications::CircularMotionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_applications::CircularMotionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CircularMotionRequest_

typedef ::simple_applications::CircularMotionRequest_<std::allocator<void> > CircularMotionRequest;

typedef boost::shared_ptr< ::simple_applications::CircularMotionRequest > CircularMotionRequestPtr;
typedef boost::shared_ptr< ::simple_applications::CircularMotionRequest const> CircularMotionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_applications::CircularMotionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_applications::CircularMotionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simple_applications::CircularMotionRequest_<ContainerAllocator1> & lhs, const ::simple_applications::CircularMotionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.radius == rhs.radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simple_applications::CircularMotionRequest_<ContainerAllocator1> & lhs, const ::simple_applications::CircularMotionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simple_applications

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simple_applications::CircularMotionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_applications::CircularMotionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_applications::CircularMotionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_applications::CircularMotionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_applications::CircularMotionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_applications::CircularMotionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_applications::CircularMotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34d1b51a3aa2a07a0194bc3c5de27677";
  }

  static const char* value(const ::simple_applications::CircularMotionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34d1b51a3aa2a07aULL;
  static const uint64_t static_value2 = 0x0194bc3c5de27677ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_applications::CircularMotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_applications/CircularMotionRequest";
  }

  static const char* value(const ::simple_applications::CircularMotionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_applications::CircularMotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 radius\n"
;
  }

  static const char* value(const ::simple_applications::CircularMotionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_applications::CircularMotionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CircularMotionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_applications::CircularMotionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_applications::CircularMotionRequest_<ContainerAllocator>& v)
  {
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_APPLICATIONS_MESSAGE_CIRCULARMOTIONREQUEST_H
