(cl:defpackage fundamentals-msg
  (:use )
  (:export
   "<BATTERYSTATUS>"
   "BATTERYSTATUS"
   "<MISSIONSTATUSACTION>"
   "MISSIONSTATUSACTION"
   "<MISSIONSTATUSACTIONFEEDBACK>"
   "MISSIONSTATUSACTIONFEEDBACK"
   "<MISSIONSTATUSACTIONGOAL>"
   "MISSIONSTATUSACTIONGOAL"
   "<MISSIONSTATUSACTIONRESULT>"
   "MISSIONSTATUSACTIONRESULT"
   "<MISSIONSTATUSFEEDBACK>"
   "MISSIONSTATUSFEEDBACK"
   "<MISSIONSTATUSGOAL>"
   "MISSIONSTATUSGOAL"
   "<MISSIONSTATUSRESULT>"
   "MISSIONSTATUSRESULT"
  ))

