; Auto-generated. Do not edit!


(cl:in-package fundamentals-msg)


;//! \htmlinclude MissionStatusGoal.msg.html

(cl:defclass <MissionStatusGoal> (roslisp-msg-protocol:ros-message)
  ((value
    :reader value
    :initarg :value
    :type cl:integer
    :initform 0))
)

(cl:defclass MissionStatusGoal (<MissionStatusGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MissionStatusGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MissionStatusGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fundamentals-msg:<MissionStatusGoal> is deprecated: use fundamentals-msg:MissionStatusGoal instead.")))

(cl:ensure-generic-function 'value-val :lambda-list '(m))
(cl:defmethod value-val ((m <MissionStatusGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fundamentals-msg:value-val is deprecated.  Use fundamentals-msg:value instead.")
  (value m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MissionStatusGoal>) ostream)
  "Serializes a message object of type '<MissionStatusGoal>"
  (cl:let* ((signed (cl:slot-value msg 'value)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MissionStatusGoal>) istream)
  "Deserializes a message object of type '<MissionStatusGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'value) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MissionStatusGoal>)))
  "Returns string type for a message object of type '<MissionStatusGoal>"
  "fundamentals/MissionStatusGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MissionStatusGoal)))
  "Returns string type for a message object of type 'MissionStatusGoal"
  "fundamentals/MissionStatusGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MissionStatusGoal>)))
  "Returns md5sum for a message object of type '<MissionStatusGoal>"
  "b3087778e93fcd34cc8d65bc54e850d1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MissionStatusGoal)))
  "Returns md5sum for a message object of type 'MissionStatusGoal"
  "b3087778e93fcd34cc8d65bc54e850d1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MissionStatusGoal>)))
  "Returns full string definition for message of type '<MissionStatusGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MissionStatusGoal)))
  "Returns full string definition for message of type 'MissionStatusGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MissionStatusGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MissionStatusGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MissionStatusGoal
    (cl:cons ':value (value msg))
))
