; Auto-generated. Do not edit!


(cl:in-package fundamentals-msg)


;//! \htmlinclude MissionStatusFeedback.msg.html

(cl:defclass <MissionStatusFeedback> (roslisp-msg-protocol:ros-message)
  ((ratio
    :reader ratio
    :initarg :ratio
    :type cl:string
    :initform ""))
)

(cl:defclass MissionStatusFeedback (<MissionStatusFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MissionStatusFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MissionStatusFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fundamentals-msg:<MissionStatusFeedback> is deprecated: use fundamentals-msg:MissionStatusFeedback instead.")))

(cl:ensure-generic-function 'ratio-val :lambda-list '(m))
(cl:defmethod ratio-val ((m <MissionStatusFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader fundamentals-msg:ratio-val is deprecated.  Use fundamentals-msg:ratio instead.")
  (ratio m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MissionStatusFeedback>) ostream)
  "Serializes a message object of type '<MissionStatusFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'ratio))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'ratio))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MissionStatusFeedback>) istream)
  "Deserializes a message object of type '<MissionStatusFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'ratio) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'ratio) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MissionStatusFeedback>)))
  "Returns string type for a message object of type '<MissionStatusFeedback>"
  "fundamentals/MissionStatusFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MissionStatusFeedback)))
  "Returns string type for a message object of type 'MissionStatusFeedback"
  "fundamentals/MissionStatusFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MissionStatusFeedback>)))
  "Returns md5sum for a message object of type '<MissionStatusFeedback>"
  "9d421494c6ac860ca5661fb574da8e84")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MissionStatusFeedback)))
  "Returns md5sum for a message object of type 'MissionStatusFeedback"
  "9d421494c6ac860ca5661fb574da8e84")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MissionStatusFeedback>)))
  "Returns full string definition for message of type '<MissionStatusFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string ratio~%~%# The ordering above is:~%# client request~%# server response~%# action feedback~%~%# When you `catkin_make` and `catkin_make install` after creating this file,~%# you will have created 7 different .msg and .h files named:~%# MissionStatus~%# MissionStatusGoal~%# MissionStatusResult~%# MissionStatusFeedback~%# MissionStatusAction~%# MissionStatusActionResult~%# MissionStatusActionFeedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MissionStatusFeedback)))
  "Returns full string definition for message of type 'MissionStatusFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string ratio~%~%# The ordering above is:~%# client request~%# server response~%# action feedback~%~%# When you `catkin_make` and `catkin_make install` after creating this file,~%# you will have created 7 different .msg and .h files named:~%# MissionStatus~%# MissionStatusGoal~%# MissionStatusResult~%# MissionStatusFeedback~%# MissionStatusAction~%# MissionStatusActionResult~%# MissionStatusActionFeedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MissionStatusFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'ratio))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MissionStatusFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MissionStatusFeedback
    (cl:cons ':ratio (ratio msg))
))
