// Generated by gencpp from file fundamentals/BatteryStatus.msg
// DO NOT EDIT!


#ifndef FUNDAMENTALS_MESSAGE_BATTERYSTATUS_H
#define FUNDAMENTALS_MESSAGE_BATTERYSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fundamentals
{
template <class ContainerAllocator>
struct BatteryStatus_
{
  typedef BatteryStatus_<ContainerAllocator> Type;

  BatteryStatus_()
    : percentage()  {
    }
  BatteryStatus_(const ContainerAllocator& _alloc)
    : percentage(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _percentage_type;
  _percentage_type percentage;





  typedef boost::shared_ptr< ::fundamentals::BatteryStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fundamentals::BatteryStatus_<ContainerAllocator> const> ConstPtr;

}; // struct BatteryStatus_

typedef ::fundamentals::BatteryStatus_<std::allocator<void> > BatteryStatus;

typedef boost::shared_ptr< ::fundamentals::BatteryStatus > BatteryStatusPtr;
typedef boost::shared_ptr< ::fundamentals::BatteryStatus const> BatteryStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fundamentals::BatteryStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fundamentals::BatteryStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fundamentals::BatteryStatus_<ContainerAllocator1> & lhs, const ::fundamentals::BatteryStatus_<ContainerAllocator2> & rhs)
{
  return lhs.percentage == rhs.percentage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fundamentals::BatteryStatus_<ContainerAllocator1> & lhs, const ::fundamentals::BatteryStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fundamentals

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fundamentals::BatteryStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fundamentals::BatteryStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fundamentals::BatteryStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fundamentals::BatteryStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fundamentals::BatteryStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fundamentals::BatteryStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fundamentals::BatteryStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6350b3b07dc3f2a6f395a2cf49c5e277";
  }

  static const char* value(const ::fundamentals::BatteryStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6350b3b07dc3f2a6ULL;
  static const uint64_t static_value2 = 0xf395a2cf49c5e277ULL;
};

template<class ContainerAllocator>
struct DataType< ::fundamentals::BatteryStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fundamentals/BatteryStatus";
  }

  static const char* value(const ::fundamentals::BatteryStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fundamentals::BatteryStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string percentage\n"
;
  }

  static const char* value(const ::fundamentals::BatteryStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fundamentals::BatteryStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BatteryStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fundamentals::BatteryStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fundamentals::BatteryStatus_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUNDAMENTALS_MESSAGE_BATTERYSTATUS_H
