// Generated by gencpp from file fundamentals/MissionStatusResult.msg
// DO NOT EDIT!


#ifndef FUNDAMENTALS_MESSAGE_MISSIONSTATUSRESULT_H
#define FUNDAMENTALS_MESSAGE_MISSIONSTATUSRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fundamentals
{
template <class ContainerAllocator>
struct MissionStatusResult_
{
  typedef MissionStatusResult_<ContainerAllocator> Type;

  MissionStatusResult_()
    : finish()  {
    }
  MissionStatusResult_(const ContainerAllocator& _alloc)
    : finish(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _finish_type;
  _finish_type finish;





  typedef boost::shared_ptr< ::fundamentals::MissionStatusResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fundamentals::MissionStatusResult_<ContainerAllocator> const> ConstPtr;

}; // struct MissionStatusResult_

typedef ::fundamentals::MissionStatusResult_<std::allocator<void> > MissionStatusResult;

typedef boost::shared_ptr< ::fundamentals::MissionStatusResult > MissionStatusResultPtr;
typedef boost::shared_ptr< ::fundamentals::MissionStatusResult const> MissionStatusResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fundamentals::MissionStatusResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fundamentals::MissionStatusResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fundamentals::MissionStatusResult_<ContainerAllocator1> & lhs, const ::fundamentals::MissionStatusResult_<ContainerAllocator2> & rhs)
{
  return lhs.finish == rhs.finish;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fundamentals::MissionStatusResult_<ContainerAllocator1> & lhs, const ::fundamentals::MissionStatusResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fundamentals

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fundamentals::MissionStatusResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fundamentals::MissionStatusResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fundamentals::MissionStatusResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fundamentals::MissionStatusResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fundamentals::MissionStatusResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fundamentals::MissionStatusResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fundamentals::MissionStatusResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30f39227304d5212717dd7074603f5c9";
  }

  static const char* value(const ::fundamentals::MissionStatusResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30f39227304d5212ULL;
  static const uint64_t static_value2 = 0x717dd7074603f5c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::fundamentals::MissionStatusResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fundamentals/MissionStatusResult";
  }

  static const char* value(const ::fundamentals::MissionStatusResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fundamentals::MissionStatusResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string finish\n"
;
  }

  static const char* value(const ::fundamentals::MissionStatusResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fundamentals::MissionStatusResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionStatusResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fundamentals::MissionStatusResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fundamentals::MissionStatusResult_<ContainerAllocator>& v)
  {
    s << indent << "finish: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.finish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUNDAMENTALS_MESSAGE_MISSIONSTATUSRESULT_H
